"use client";
import {useEffect,useState} from "react";
import {acceptMeterSuggestion,rejectMeterSuggestion,type ImportedPoem,type MeterCandidate} from "./corpus";
import type {CorpusWorkspace} from "./corpus-db";import type {ServerProject} from "./projects-dialog";
type Job={id:string;type:string;status:string;progress:number;result?:{processed_lines?:number;ambiguous_lines?:number;insufficient_lines?:number};error:string|null};
const api=async<T,>(u:string,i?:RequestInit):Promise<T>=>{const r=await fetch(u,i),d=await r.json();if(!r.ok)throw new Error(d.detail?.message??"Ошибка API");return d};
export function MeterDialog({project,workspace,onProject,onWorkspace,onClose}:{project:ServerProject;workspace:CorpusWorkspace;onProject:(p:ServerProject)=>void;onWorkspace:(w:CorpusWorkspace)=>void;onClose:()=>void}){
 const [current,setCurrent]=useState(project),[space,setSpace]=useState(workspace),[selected,setSelected]=useState(new Set(workspace.activeId?[workspace.activeId]:[])),[job,setJob]=useState<Job|null>(null),[onlyReview,setOnlyReview]=useState(false),[message,setMessage]=useState("");
 const publish=(p:ServerProject)=>{setCurrent(p);setSpace(p.workspace!);onProject(p);onWorkspace(p.workspace!)};
 useEffect(()=>{Promise.all([api<ServerProject>(`/api/v1/projects/${project.id}`),api<Job[]>(`/api/v1/projects/${project.id}/jobs`)]).then(([p,j])=>{publish(p);setJob(j.find(x=>x.type==="meter_analysis"&&["queued","running","cancel_requested"].includes(x.status))??j.find(x=>x.type==="meter_analysis")??null)}).catch(e=>setMessage(e.message))},[project.id]);
 useEffect(()=>{if(!job||!["queued","running","cancel_requested"].includes(job.status))return;const t=setInterval(()=>api<Job>(`/api/v1/jobs/${job.id}`).then(async j=>{setJob(j);if(!["queued","running","cancel_requested"].includes(j.status))publish(await api(`/api/v1/projects/${project.id}`))}).catch(e=>setMessage(e.message)),700);return()=>clearInterval(t)},[job?.id,job?.status,project.id]);
 const save=(poems:ImportedPoem[])=>api<ServerProject>(`/api/v1/projects/${current.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({name:current.name,schema_version:current.schema_version,revision:current.revision,workspace:{...space,poems}})}).then(publish);
 const start=async(line?:{poemId:string;lineId:string})=>{const synced=await api<ServerProject>(`/api/v1/projects/${current.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({name:current.name,schema_version:current.schema_version,revision:current.revision,workspace:space})});publish(synced);setJob(await api(`/api/v1/projects/${current.id}/meter/jobs`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({poem_ids:line?[line.poemId]:[...selected],line_ids:line?[line.lineId]:undefined,revision:synced.revision,analyzer_version:"meter-1.0.0"})}))};
 const change=(poemId:string,lineId:string,action:"accept"|"reject",candidate?:MeterCandidate)=>save(space.poems.map(p=>p.id!==poemId?p:{...p,dirty:true,modified:action==="accept"||p.modified,lines:p.lines.map(l=>l.id!==lineId?l:action==="accept"?acceptMeterSuggestion(l,candidate):rejectMeterSuggestion(l))}));
 const rows=space.poems.flatMap(poem=>poem.lines.filter(line=>line.meterSuggestion&&(!onlyReview||["ambiguous","insufficient"].includes(line.meterSuggestion.quality))).map(line=>({poem,line,s:line.meterSuggestion!}))), exact=rows.filter(x=>x.s.state==="pending"&&x.s.quality==="exact"&&x.s.candidates.length===1&&!x.line.meter&&!x.line.feet&&!x.line.scheme);
 return <div className="projects-backdrop"><section className="stress-dialog"><header><div><p>Детерминированно · без сети</p><h2>Метрический анализ</h2></div><button onClick={onClose}>×</button></header><p className="project-note">Используются только подтверждённые ударения текста. Предложения не экспортируются до принятия.</p><div className="stress-selection"><div><button onClick={()=>setSelected(new Set(space.activeId?[space.activeId]:[]))}>Текущее</button><button onClick={()=>setSelected(new Set(space.poems.map(p=>p.id)))}>Все</button></div>{space.poems.map(p=><label key={p.id}><input type="checkbox" checked={selected.has(p.id)} onChange={e=>setSelected(old=>{const n=new Set(old);e.target.checked?n.add(p.id):n.delete(p.id);return n})}/>{p.title||"Без названия"} ({p.lines.length})</label>)}<button className="button primary" disabled={!selected.size||!!job&&["queued","running","cancel_requested"].includes(job.status)} onClick={()=>start()}>Запустить</button></div>{job&&<div className="stress-job"><b>{job.status}</b><progress value={job.progress} max={1}/><span>{job.result?.processed_lines??0} строк · неоднозначных {job.result?.ambiguous_lines??0} · недостаточных {job.result?.insufficient_lines??0}</span>{["queued","running"].includes(job.status)&&<button onClick={()=>api(`/api/v1/jobs/${job.id}/cancel`,{method:"POST"}).then(()=>setJob({...job,status:"cancel_requested"}))}>Отменить</button>}</div>}<div className="stress-review-tools"><label><input type="checkbox" checked={onlyReview} onChange={e=>setOnlyReview(e.target.checked)}/> Только требующие проверки</label><button disabled={!exact.length} onClick={()=>{if(confirm(`Будет принято ${exact.length} строк и ${exact.length*4} полей.`))save(space.poems.map(p=>({...p,lines:p.lines.map(l=>exact.some(x=>x.line.id===l.id)?acceptMeterSuggestion(l):l)})));}}>Принять exact ({exact.length})</button></div><div className="stress-results">{rows.map(({poem,line,s})=><article key={line.id} className={s.state}><small>{poem.title} · {s.quality} · {s.state}</small><div><span>{s.syllables.map(x=><i key={x.index} title={`${x.start}:${x.end}`}>{x.stress==="stressed"?"◉":x.stress==="unknown"?"?":"○"}{x.text}</i>)}</span><strong>{s.accentSequence}</strong></div><p>{s.explanation}</p><div>{s.candidates.map(c=><button key={`${c.meter}-${c.anacrusis}`} onClick={()=>change(poem.id,line.id,"accept",c)}>{c.meter}{c.feetOrIctuses}: икты {c.ictusPositions.join(",")} · нарушений {c.violations.length}</button>)}<button onClick={()=>change(poem.id,line.id,"reject")}>Отклонить</button><button onClick={()=>start({poemId:poem.id,lineId:line.id})}>Повторить</button></div></article>)}</div><fieldset><legend>Экспертные решения R016/R017</legend><label>Границы сегментов <input placeholder="1–8; 9–16"/></label><label><input type="checkbox"/> Объединить соседние графические фрагменты только для анализа</label></fieldset>{message&&<p>{message}</p>}</section></div>;
}
