"use client";
import { useEffect, useRef, useState } from "react";

type Doc = {id:string; original_name:string; status:string; page_count:number; revision:number; pages?:Page[]};
type Page = {page_number:number; edited_text:string; method:string; warnings:string[]; confidence:number|null; review_status:string; revision:number};
export function PdfImportDialog({onClose,onReviewed}:{onClose:()=>void;onReviewed:(name:string,text:string)=>void}) {
  const [project,setProject]=useState(""); const [docs,setDocs]=useState<Doc[]>([]); const [active,setActive]=useState<Doc|null>(null); const [busy,setBusy]=useState(false); const input=useRef<HTMLInputElement>(null);
  const load=async(id:string)=>{const r=await fetch(`/api/v1/sources/${id}`);if(r.ok)setActive(await r.json())};
  useEffect(()=>{if(active?.status==="queued"||active?.status==="extracting"){const t=setTimeout(()=>load(active.id),1200);return()=>clearTimeout(t)}},[active]);
  const upload=async(files:FileList)=>{if(!project)return alert("Укажите UUID серверного проекта");setBusy(true);const queue=[...files];const results:Doc[]=[];let next=0;async function worker(){while(next<queue.length){const order=next++;const data=new FormData();data.append("file",queue[order]);data.append("upload_order",String(order));const r=await fetch(`/api/v1/projects/${project}/sources`,{method:"POST",body:data});if(!r.ok){alert((await r.text()));continue}const doc=await r.json();results.push(doc);await fetch(`/api/v1/sources/${doc.id}/extract`,{method:"POST"})}}await Promise.all([worker(),worker()]);setDocs(results.sort((a,b)=>a.original_name.localeCompare(b.original_name)));setBusy(false)};
  const patch=async(page:Page,value:Partial<Page>)=>{const r=await fetch(`/api/v1/sources/${active!.id}/pages/${page.page_number}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...value,revision:page.revision})});if(r.ok)load(active!.id)};
  const approve=async()=>{const r=await fetch(`/api/v1/sources/${active!.id}/approve`,{method:"POST"});if(!r.ok)return alert("Подтвердите или исключите каждую страницу");const text=active!.pages!.filter(p=>p.review_status!=="excluded").map(p=>p.edited_text).join("\n\n");onReviewed(active!.original_name,text)};
  return <div className="raw-dialog-backdrop"><section className="raw-dialog pdf-review" role="dialog" aria-modal="true"><header className="raw-dialog-header"><div><p>Полностью локальная обработка · Tesseract rus+eng</p><h2>Импорт PDF и обязательная проверка</h2></div><button className="raw-dialog-close" onClick={onClose}>×</button></header>
    <div className="raw-dialog-toolbar"><label>UUID проекта<input value={project} onChange={e=>setProject(e.target.value)} placeholder="из окна «Проекты»"/></label><input hidden ref={input} type="file" accept="application/pdf,.pdf" multiple onChange={e=>e.target.files&&upload(e.target.files)}/><button className="button primary" disabled={busy} onClick={()=>input.current?.click()}>{busy?"Загрузка…":"Выбрать несколько PDF"}</button></div>
    <div className="pdf-docs">{docs.map(d=><button key={d.id} onClick={()=>load(d.id)}><strong>{d.original_name}</strong><small>{d.page_count} стр. · {d.status}</small></button>)}</div>
    {active&&<><p className="raw-help">PDF не равен одному стихотворению. Автор, заголовки и границы будут проверены в существующем импортёре после подтверждения страниц.</p><div className="pdf-pages">{active.pages?.map(p=><article key={p.page_number}><div><strong>Страница {p.page_number}</strong> · {p.method==="ocr"?"OCR":"текстовый слой"} {p.confidence!=null&&`· ${p.confidence.toFixed(0)}%`}<img src={`/api/v1/sources/${active.id}/preview/${p.page_number}`} alt={`Страница ${p.page_number}`}/></div><div>{p.warnings.map(w=><p className="raw-message" key={w}>{w}</p>)}<textarea value={p.edited_text} onChange={e=>setActive({...active,pages:active.pages!.map(x=>x.page_number===p.page_number?{...x,edited_text:e.target.value}:x)})} onBlur={()=>patch(p,{edited_text:p.edited_text})}/><button className="button secondary" onClick={()=>patch(p,{review_status:"approved"})}>Подтвердить</button><button className="delete" onClick={()=>patch(p,{review_status:"excluded"})}>Исключить</button></div></article>)}</div><footer className="raw-dialog-footer"><button className="button primary" disabled={active.status!=="review"} onClick={approve}>Подтвердить документ и проверить границы</button></footer></>}
  </section></div>;
}
