"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import type { ServerProject } from "./projects-dialog";
import { canImportPdf, jobMatchesPage, planPdfBatch, trackOcrJob, type TrackedOcrJob } from "./pdf-import-state";

type Page={page_number:number;edited_text:string;embedded_text:string|null;ocr_text:string|null;method:string|null;warnings:string[];confidence:number|null;review_status:string;revision:number};
type Job={id:string;status:string;progress:number;error:string|null};
type Doc={id:string;original_name:string;status:string;page_count:number;upload_order:number;revision:number;pages?:Page[];error?:string;job?:Job;ocr_jobs?:Array<Job&{document_id:string;page_number:number}>};
const api=async<T,>(url:string,init?:RequestInit):Promise<T>=>{const r=await fetch(url,init);const data=r.status===204?null:await r.json();if(!r.ok)throw new Error(data?.detail?.message||"Ошибка API");return data};
export function PdfImportDialog({project,onClose,onReviewed}:{project:ServerProject|null;onClose:()=>void;onReviewed:(doc:Doc,text:string)=>Promise<void>}){
 const [docs,setDocs]=useState<Doc[]>([]),[active,setActive]=useState<Doc|null>(null),[pageNo,setPageNo]=useState(1),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[ocrJobs,setOcrJobs]=useState<Record<string,TrackedOcrJob>>({});const input=useRef<HTMLInputElement>(null);
 const activeId=active?.id;
 const refresh=useCallback(async()=>{if(!project)return;try{const values=await api<Doc[]>(`/api/v1/projects/${project.id}/sources`);setDocs(values);setOcrJobs(items=>{const next={...items};for(const source of values)for(const job of source.ocr_jobs??[])next[`${source.id}:${job.page_number}`]={...job,documentId:source.id,pageNumber:job.page_number};return next});if(activeId){const found=values.find(x=>x.id===activeId);if(found)setActive(await api(`/api/v1/sources/${found.id}`))}}catch(e){setMessage((e as Error).message)}},[project,activeId]);
 useEffect(()=>{const timer=setTimeout(refresh,0);return()=>clearTimeout(timer)},[refresh]);useEffect(()=>{const running=Object.values(ocrJobs).filter(job=>["queued","running","cancel_requested"].includes(job.status));if(!running.length)return;const timer=setTimeout(async()=>{for(const tracked of running){try{const job=await api<Job>(`/api/v1/jobs/${tracked.id}`);setOcrJobs(items=>({...items,[`${tracked.documentId}:${tracked.pageNumber}`]:{...tracked,...job}}));if(job.status==="succeeded"){const source=await api<Doc>(`/api/v1/sources/${tracked.documentId}`);if(active?.id===tracked.documentId)setActive(source);setDocs(items=>items.map(item=>item.id===source.id?source:item))}}catch(e){setMessage((e as Error).message)}}},800);return()=>clearTimeout(timer)},[ocrJobs,active]);useEffect(()=>{if(docs.some(d=>["queued","extracting"].includes(d.status))){const t=setTimeout(refresh,1200);return()=>clearTimeout(t)}},[docs,refresh]);
 const open=async(d:Doc)=>{try{setActive(await api(`/api/v1/sources/${d.id}`));setPageNo(1)}catch(e){setMessage((e as Error).message)}};
 const upload=async(files:FileList)=>{if(!project)return;const projectId=project.id;setBusy(true);setMessage("");let next=0;const batch=planPdfBatch(docs,[...files]);async function worker(){while(next<batch.length){const item=batch[next++];const form=new FormData();form.append("file",item.file);form.append("upload_order",String(item.uploadOrder));try{const d=await api<Doc>(`/api/v1/projects/${projectId}/sources`,{method:"POST",body:form});await api(`/api/v1/sources/${d.id}/extract`,{method:"POST"})}catch(e){setMessage((e as Error).message)}}}await Promise.all([worker(),worker()]);setBusy(false);await refresh()};
 const save=async(page:Page,value:Partial<Page>)=>{try{await api(`/api/v1/sources/${active!.id}/pages/${page.page_number}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...value,revision:page.revision})});await open(active!)}catch(e){setMessage((e as Error).message)}};
 const current=active?.pages?.find(p=>p.page_number===pageNo);
 const remove=async()=>{if(!active||!confirm("Удалить PDF и результаты распознавания?"))return;try{await api(`/api/v1/sources/${active.id}`,{method:"DELETE"});setActive(null);await refresh()}catch(e){setMessage((e as Error).message)}};
 if(!project)return <div className="raw-dialog-backdrop"><section className="raw-dialog pdf-review"><header className="raw-dialog-header"><h2>Импорт PDF</h2><button className="raw-dialog-close" onClick={onClose}>×</button></header><p className="raw-message">Сначала создайте или откройте серверный проект в окне «Проекты». PDF и исправления должны быть связаны с сохраняемым проектом.</p></section></div>;
 return <div className="raw-dialog-backdrop"><section className="raw-dialog pdf-review" role="dialog" aria-modal="true"><header className="raw-dialog-header"><div><p>{project.name} · локальный Tesseract rus+eng</p><h2>Постраничная проверка PDF</h2></div><button className="raw-dialog-close" onClick={onClose}>×</button></header>
 <div className="raw-dialog-toolbar"><input hidden ref={input} type="file" accept="application/pdf,.pdf" multiple onChange={e=>e.target.files&&upload(e.target.files)}/><button className="button primary" disabled={busy} onClick={()=>input.current?.click()}>{busy?"Загрузка…":"Выбрать несколько PDF"}</button></div>{message&&<p className="raw-message" role="alert">{message}</p>}
 <div className="pdf-docs">{docs.map(d=><button key={d.id} className={active?.id===d.id?"active":""} onClick={()=>open(d)}><strong>{d.original_name}</strong><small>{d.page_count} стр. · {d.status}</small><progress max="1" value={d.job?.progress??(d.status==="review"||d.status==="approved"?1:0)}/><small>{Math.round((d.job?.progress??0)*100)}%</small>{d.error&&<small>{d.error}</small>}</button>)}</div>
 {active&&<><div className="pdf-actions"><a className="button secondary" href={`/api/v1/sources/${active.id}/download`}>Оригинал</a><a className="button secondary" href={`/api/v1/sources/${active.id}/text`}>TXT</a><a className="button secondary" href={`/api/v1/sources/${active.id}/json`}>JSON</a><button className="button secondary" onClick={async()=>{try{const job=active.job;if(job&&["queued","running","cancel_requested"].includes(job.status))await api(`/api/v1/jobs/${job.id}/cancel`,{method:"POST"});await refresh()}catch(e){setMessage((e as Error).message)}}}>Отменить</button><button className="delete" onClick={remove}>Удалить</button></div>
 <nav className="pdf-page-nav">{active.pages?.map(p=><button key={p.page_number} className={p.page_number===pageNo?"active":p.review_status} onClick={()=>setPageNo(p.page_number)}>{p.page_number} · {p.review_status}</button>)}</nav>
 {current&&<article className="pdf-current-page"><div><strong>Страница {current.page_number}</strong> · {current.method||"ошибка"} {current.confidence!=null&&`· ${current.confidence.toFixed(0)}%`}<img src={`/api/v1/sources/${active.id}/preview/${current.page_number}`} alt={`Страница ${current.page_number}`}/></div><div>{current.warnings.map(w=><p className="raw-message" key={w}>{w}</p>)}<textarea disabled={active.status!=="review"} value={current.edited_text} onChange={e=>setActive({...active,pages:active.pages!.map(p=>p.page_number===pageNo?{...p,edited_text:e.target.value}:p)})}/><button disabled={active.status!=="review"} className="button secondary" onClick={()=>save(current,{edited_text:current.edited_text})}>Сохранить текст</button>{current.embedded_text!=null&&<button disabled={active.status!=="review"} className="button secondary" onClick={()=>save(current,{method:"embedded_text"})}>Встроенный текст</button>}{current.ocr_text!=null&&<button disabled={active.status!=="review"} className="button secondary" onClick={()=>save(current,{method:"ocr"})}>OCR</button>}<button disabled={active.status!=="review"} className="button secondary" onClick={async()=>{try{const created=await api<{job_id:string;status:string}>(`/api/v1/sources/${active.id}/pages/${pageNo}/ocr?revision=${current.revision}`,{method:"POST"});setOcrJobs(items=>trackOcrJob(items,{id:created.job_id,status:created.status,progress:0,error:null,documentId:active.id,pageNumber:pageNo}))}catch(e){setMessage((e as Error).message)}}}>Повторить OCR</button>{jobMatchesPage(ocrJobs[`${active.id}:${pageNo}`]??null,active.id,pageNo)&&<span>OCR: {ocrJobs[`${active.id}:${pageNo}`].status} · {Math.round(ocrJobs[`${active.id}:${pageNo}`].progress*100)}% {ocrJobs[`${active.id}:${pageNo}`].error}<button disabled={!["queued","running"].includes(ocrJobs[`${active.id}:${pageNo}`].status)} onClick={async()=>{const tracked=ocrJobs[`${active.id}:${pageNo}`],job=await api<Job>(`/api/v1/jobs/${tracked.id}/cancel`,{method:"POST"});setOcrJobs(items=>({...items,[`${active.id}:${pageNo}`]:{...tracked,...job}}))}}>Отменить OCR</button></span>}<button disabled={active.status!=="review"} className="button primary" onClick={()=>save(current,{edited_text:current.edited_text,review_status:"approved"})}>Сохранить и подтвердить</button><button disabled={active.status!=="review"} className="delete" onClick={()=>save(current,{review_status:"excluded"})}>Исключить</button></div></article>}
 <footer className="raw-dialog-footer"><button className="button primary" disabled={!canImportPdf(active.status)||Object.values(ocrJobs).some(job=>job.documentId===active.id&&["queued","running","cancel_requested"].includes(job.status))} onClick={async()=>{try{let source=active;if(active.status==="review"){source=await api<Doc>(`/api/v1/sources/${active.id}/approve`,{method:"POST"});setActive(source);setDocs(items=>items.map(item=>item.id===source.id?source:item))}const text=await (await fetch(`/api/v1/sources/${active.id}/text`)).text();await onReviewed(source,text)}catch(e){setMessage((e as Error).message)}}}>{active.status==="approved"?"Повторить сохранение в проект":"Подтвердить документ и проверить границы"}</button></footer></>}</section></div>;
}
