"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import type { CorpusWorkspace } from "./corpus-db";

export type ServerProject = { id:string; name:string; schema_version:number; revision:number; created_at:string; updated_at:string; workspace?:CorpusWorkspace };
type Project = ServerProject;
type Job = { id:string; status:string; result:unknown; error:string|null };
const request = async <T,>(url:string, init?:RequestInit):Promise<T> => { const response=await fetch(url, init); const data=response.status===204?null:await response.json(); if(!response.ok) { const error=new Error(data?.detail?.message ?? data?.message ?? "Ошибка API") as Error & {status:number; detail?:unknown}; error.status=response.status; error.detail=data?.detail; throw error; } return data; };
export function makeBackup(project:Project) { return { schema_version:project.schema_version, name:project.name, workspace:project.workspace, backed_up_at:new Date().toISOString() }; }
export function validateBackup(value:unknown): {schema_version:number;name:string;workspace:CorpusWorkspace} { if(!value || typeof value!=="object") throw new Error("JSON должен быть объектом"); const v=value as Record<string,unknown>, w=v.workspace as Record<string,unknown>; if(!Number.isInteger(v.schema_version)||typeof v.name!=="string"||!w||!Array.isArray(w.corpora)||!Array.isArray(w.poems)||!(w.activeId===null||typeof w.activeId==="string")||!Array.isArray(w.queue)) throw new Error("Некорректная структура резервной копии"); return {schema_version:v.schema_version as number,name:v.name,workspace:w as CorpusWorkspace}; }
export function ProjectsDialog({workspace,onLoad,onProject,onClose}:{workspace:CorpusWorkspace;onLoad:(w:CorpusWorkspace)=>void;onProject:(p:ServerProject|null)=>void;onClose:()=>void}) {
 const [projects,setProjects]=useState<Project[]>([]), [current,setCurrent]=useState<Project|null>(null), [jobs,setJobs]=useState<Job[]>([]), [name,setName]=useState("Новый проект"), [message,setMessage]=useState(""); const importRef=useRef<HTMLInputElement>(null);
 const refresh=useCallback(()=>request<Project[]>("/api/v1/projects").then(setProjects).catch(e=>setMessage(e.message)),[]);
 useEffect(()=>{refresh()},[refresh]);
 const create=async (backup?:{schema_version:number;name:string;workspace:CorpusWorkspace})=>{try {const p=await request<Project>("/api/v1/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(backup??{name,schema_version:1,workspace})});setCurrent(p);setName(p.name);setJobs([]);onProject(p);setMessage("Проект создан");refresh()}catch(e){setMessage((e as Error).message)}};
 const open=async(id:string)=>{if(!confirm("Заменить текущее рабочее пространство серверной копией?"))return;try{const p=await request<Project>(`/api/v1/projects/${id}`);onLoad(p.workspace!);onProject(p);setCurrent(p);setName(p.name);setMessage("Проект открыт и сохранён в IndexedDB");setJobs(await request(`/api/v1/projects/${id}/jobs`))}catch(e){setMessage((e as Error).message)}};
 const save=async()=>{if(!current)return;try{const p=await request<Project>(`/api/v1/projects/${current.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,schema_version:current.schema_version,revision:current.revision,workspace})});setCurrent(p);onProject(p);setMessage("Изменения сохранены");refresh()}catch(e){const x=e as Error & {status:number};setMessage(x.status===409?"Конфликт revision: загрузите серверную версию или создайте новый проект.":x.message)}};
 const remove=async(p:Project)=>{if(!confirm(`Необратимо удалить «${p.name}» и задания?`))return;try{await request(`/api/v1/projects/${p.id}`,{method:"DELETE"});if(current?.id===p.id){setCurrent(null);onProject(null);setJobs([])}refresh()}catch(e){setMessage((e as Error).message)}};
 const job=async()=>{if(!current)return;try{const j=await request<Job>(`/api/v1/projects/${current.id}/jobs`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"workspace_summary"})});setJobs(x=>[j,...x])}catch(e){setMessage((e as Error).message)}};
 const poll=async(j:Job)=>{try{const latest=await request<Job>(`/api/v1/jobs/${j.id}`);setJobs(x=>x.map(v=>v.id===j.id?latest:v))}catch(e){setMessage((e as Error).message)}};
 const download=()=>{if(!current?.workspace)return;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(makeBackup(current),null,2)],{type:"application/json"}));a.download=`${current.name}.ncrl-project.json`;a.click();URL.revokeObjectURL(a.href)};
 return <div className="projects-backdrop"><section className="projects-dialog"><header><h2>Серверные проекты</h2><button onClick={onClose}>×</button></header><p className="project-note">Тексты отправляются только при создании или сохранении проекта.</p><div className="project-create"><input value={name} maxLength={200} onChange={e=>setName(e.target.value)}/><button className="button primary" onClick={()=>create()}>Создать из workspace</button><input ref={importRef} hidden type="file" accept="application/json,.json" onChange={async e=>{try{const file=e.target.files?.[0];if(file){const value=validateBackup(JSON.parse(await file.text()));await create(value)}}catch(x){setMessage((x as Error).message)}finally{e.target.value=""}}}/><button className="button secondary" onClick={()=>importRef.current?.click()}>Импорт JSON</button></div>{message&&<p className="raw-message">{message}</p>}<div className="project-list">{projects.map(p=><article key={p.id}><div><strong>{p.name}</strong><small>revision {p.revision} · {new Date(p.updated_at).toLocaleString()}</small></div><button onClick={()=>open(p.id)}>Открыть</button><button className="delete" onClick={()=>remove(p)}>Удалить</button></article>)}</div>{current&&<div className="project-current"><h3>{current.name} · revision {current.revision}</h3><button className="button primary" onClick={save}>Сохранить / переименовать</button><button className="button secondary" onClick={download}>Резервная копия JSON</button><button className="button secondary" onClick={job}>Сводка проекта</button>{jobs.map(j=><div className="project-job" key={j.id}><b>{j.status}</b> {j.result != null && <code>{JSON.stringify(j.result)}</code>} {j.error}<button onClick={()=>poll(j)}>Обновить</button>{j.status==="queued"&&<button onClick={async()=>{try{await request(`/api/v1/jobs/${j.id}/cancel`,{method:"POST"});await poll(j)}catch(e){setMessage((e as Error).message)}}}>Отменить</button>}</div>)}</div>}</section></div>;
}
