"use client";
import {useEffect,useRef,useState} from "react";
import {acceptStressSuggestion,acceptStressWord,type ImportedPoem,type StressSuggestion} from "./corpus";
import type {CorpusWorkspace} from "./corpus-db";
import type {ServerProject} from "./projects-dialog";

type Model={id:string;version:string;filename:string;size:number;sha256:string;license:string;state:"not_installed"|"installing"|"installed"|"error";progress:number;error:string|null};
type Job={id:string;status:string;progress:number;result?:{processed_lines?:number;uncertain_words?:number};error:string|null};
const api=async<T,>(url:string,init?:RequestInit):Promise<T>=>{const response=await fetch(url,init),data=response.status===204?null:await response.json();if(!response.ok)throw new Error(data?.detail?.message??"Ошибка API");return data};
export const stressSelection=(poems:ImportedPoem[],mode:"all"|"current",activeId:string|null)=>new Set(mode==="all"?poems.map(poem=>poem.id):(activeId?[activeId]:[]));

export function StressDialog({project,workspace,onProject,onWorkspace,onClose}:{project:ServerProject;workspace:CorpusWorkspace;onProject:(p:ServerProject)=>void;onWorkspace:(w:CorpusWorkspace)=>void;onClose:()=>void}){
 const [models,setModels]=useState<Model[]>([]),[selected,setSelected]=useState<Set<string>>(()=>stressSelection(workspace.poems,"current",workspace.activeId)),[job,setJob]=useState<Job|null>(null),[message,setMessage]=useState(""),[uncertainOnly,setUncertainOnly]=useState(false),[threshold,setThreshold]=useState(.9);const offline=useRef<HTMLInputElement>(null);
 const refreshModels=()=>api<Model[]>("/api/v1/stress/models").then(setModels).catch(e=>setMessage(e.message));
 useEffect(()=>{refreshModels()},[]);
 useEffect(()=>{if(!models.some(item=>item.state==="installing"))return;const timer=setInterval(refreshModels,500);return()=>clearInterval(timer)},[models]);
 useEffect(()=>{if(!job||!["queued","running","cancel_requested"].includes(job.status))return;const timer=setInterval(async()=>{try{const next=await api<Job>(`/api/v1/jobs/${job.id}`);setJob(next);if(next.status==="succeeded"){const current=await api<ServerProject>(`/api/v1/projects/${project.id}`);onProject(current);onWorkspace(current.workspace!);setMessage("Предложения готовы. Они не попадут в экспорт до принятия.")}}catch(e){setMessage((e as Error).message)}},700);return()=>clearInterval(timer)},[job,project.id,onProject,onWorkspace]);
 const model=models[0],selectedPoems=workspace.poems.filter(p=>selected.has(p.id)),lineCount=selectedPoems.reduce((n,p)=>n+p.lines.length,0);
 const install=async()=>{if(!model)return;setMessage("Загружаются только файлы модели; тексты не покидают компьютер.");await api(`/api/v1/stress/models/${model.id}/${model.version}/install`,{method:"POST"});refreshModels()};
 const upload=async(file:File)=>{if(!model)return;const body=new FormData();body.append("file",file);await api(`/api/v1/stress/models/${model.id}/${model.version}/import`,{method:"POST",body});refreshModels()};
 const saveProject=async(nextWorkspace:CorpusWorkspace)=>api<ServerProject>(`/api/v1/projects/${project.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({name:project.name,schema_version:project.schema_version,revision:project.revision,workspace:nextWorkspace})});
 const start=async(target?:{poemId:string;lineId:string})=>{if(!model)return;const synced=await saveProject(workspace);onProject(synced);const next=await api<Job>(`/api/v1/projects/${project.id}/stress/jobs`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({poem_ids:target?[target.poemId]:[...selected],line_ids:target?[target.lineId]:undefined,revision:synced.revision,model_id:model.id,model_version:model.version})});setJob(next)};
 const persist=async(poems:ImportedPoem[])=>{const next=await saveProject({...workspace,poems});onProject(next);onWorkspace(next.workspace!)};
 const changeLine=async(poemId:string,lineId:string,action:"accept"|"reject"|"restore",manual?:string)=>{await persist(workspace.poems.map(poem=>poem.id!==poemId?poem:{...poem,dirty:true,modified:action==="accept"||manual!==undefined?true:poem.modified,lines:poem.lines.map(line=>{if(line.id!==lineId||!line.stressSuggestion)return line;const s=line.stressSuggestion;if(manual!==undefined)return{...line,text:manual,stressSuggestion:{...s,state:"accepted"}};if(action==="accept")return acceptStressSuggestion(line);if(action==="restore")return{...line,text:s.sourceText,stressSuggestion:{...s,state:"rejected"}};return{...line,stressSuggestion:{...s,state:"rejected"}}})}))};
 const review=workspace.poems.flatMap(poem=>poem.lines.filter(line=>line.stressSuggestion&&(uncertainOnly?line.stressSuggestion.uncertainWords.length>0:true)).map(line=>({poem,line,s:line.stressSuggestion as StressSuggestion})));
 const high=review.filter(x=>x.s.state==="pending"&&x.s.confidence>=threshold&&x.s.uncertainWords.length===0);
 return <div className="projects-backdrop"><section className="stress-dialog"><header><div><p>Локальная CPU-модель</p><h2>Автоматические ударения</h2></div><button onClick={onClose}>×</button></header><p className="project-note">Модель только предлагает разметку. Обязательна филологическая проверка; непринятые предложения не экспортируются.</p>
  <div className="stress-model">{model&&<><strong>Silero Stress {model.version}</strong><span>{(model.size/1024/1024).toFixed(1)} MiB · {model.license} · {model.state}</span><code>SHA-256 {model.sha256}</code>{model.state==="installing"&&<progress value={model.progress} max={1}/>}<button className="button primary" disabled={model.state==="installed"||model.state==="installing"} onClick={install}>Установить модель</button><button className="button secondary" onClick={()=>offline.current?.click()}>Офлайн-импорт</button><input ref={offline} hidden type="file" accept=".whl" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/><button className="button secondary" disabled={model.state!=="installed"} onClick={async()=>{await api(`/api/v1/stress/models/${model.id}/${model.version}/verify`,{method:"POST"});setMessage("SHA-256 модели подтверждён")}}>Проверить</button><button className="delete" disabled={model.state!=="installed"} onClick={async()=>{await api(`/api/v1/stress/models/${model.id}/${model.version}`,{method:"DELETE"});refreshModels()}}>Удалить</button></>}</div>
  <div className="stress-selection"><div><button onClick={()=>setSelected(stressSelection(workspace.poems,"current",workspace.activeId))}>Текущее</button><button onClick={()=>setSelected(stressSelection(workspace.poems,"all",workspace.activeId))}>Весь проект</button><button onClick={()=>setSelected(new Set())}>Снять выбор</button></div>{workspace.poems.map(poem=><label key={poem.id}><input type="checkbox" checked={selected.has(poem.id)} onChange={e=>setSelected(old=>{const n=new Set(old);if(e.target.checked)n.add(poem.id);else n.delete(poem.id);return n})}/>{poem.title||"Без названия"} <small>{poem.lines.length} стр.</small></label>)}<strong>Выбрано: {selected.size} произведений, {lineCount} строк</strong><button className="button primary" disabled={!selected.size||model?.state!=="installed"||!!job&&["queued","running"].includes(job.status)} onClick={()=>start()}>Запустить анализ</button></div>
  {job&&<div className="stress-job"><b>{job.status}</b><progress value={job.progress} max={1}/><span>{Math.round(job.progress*100)}% · {job.result?.processed_lines??0} строк · {job.result?.uncertain_words??0} сомнительных слов</span>{["queued","running"].includes(job.status)&&<button onClick={()=>api(`/api/v1/jobs/${job.id}/cancel`,{method:"POST"}).then(()=>setJob({...job,status:"cancel_requested"}))}>Отменить</button>}{job.error}</div>}
  <div className="stress-review-tools"><label><input type="checkbox" checked={uncertainOnly} onChange={e=>setUncertainOnly(e.target.checked)}/> Только сомнительные</label><label>Высокая уверенность ≥ <input type="number" min="0" max="1" step=".05" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><button disabled={!high.length} onClick={async()=>{if(confirm(`Будет изменено строк: ${high.length}. Продолжить?`)){let poems=workspace.poems;for(const item of high)poems=poems.map(p=>p.id!==item.poem.id?p:{...p,modified:true,lines:p.lines.map(l=>l.id===item.line.id?acceptStressSuggestion(l):l)});await persist(poems)}}}>Принять высокую уверенность ({high.length})</button></div>
  <div className="stress-results">{review.map(({poem,line,s})=><article key={`${poem.id}-${line.id}`} className={s.state}><small>{poem.title} · {s.state} · {Math.round(s.confidence*100)}%</small><div><span>{s.sourceText}</span><strong>{s.suggestedText}</strong></div>{s.uncertainWords.length>0&&<div className="stress-words">{s.words.map((word,wordIndex)=>(word.ambiguous||word.warning)&&<span key={wordIndex}>{word.original}: {[word.position,...word.alternatives].filter((value):value is number=>value!==null).map(position=><button key={position} onClick={()=>persist(workspace.poems.map(p=>p.id!==poem.id?p:{...p,modified:true,lines:p.lines.map(l=>l.id===line.id?acceptStressWord(l,wordIndex,position):l)}))}>ударение {position+1}</button>)}</span>)}</div>}<div><button onClick={()=>changeLine(poem.id,line.id,"accept")}>Принять строку</button><button onClick={()=>changeLine(poem.id,line.id,"reject")}>Отклонить</button><button onClick={()=>changeLine(poem.id,line.id,"restore")}>Восстановить исходную</button><button onClick={()=>{const text=prompt("Исправьте строку",line.text);if(text!==null)changeLine(poem.id,line.id,"accept",text)}}>Исправить вручную</button>{s.state==="stale"&&<button onClick={()=>start({poemId:poem.id,lineId:line.id})}>Повторить строку</button>}</div></article>)}</div>{message&&<p className="raw-message">{message}</p>}</section></div>
}
